### ISSUE TITLE
Add blog post(s)

### ISSUE THREAD

**Issue by tobyhodges** [czi-catalystproject/catalyst-project#2]
We should add at least one blog post to the site, e.g. announcing the communities onboarded so far, or the creation of the Zenodo community, or summarising the governance calls, etc.

**Comment by Tajuddeen1** [comment]
I wanted to write about the onboarded communities but wanted to get some inputs from the communities themselves. I definitely need more time

**Comment by jnywong** [comment]
Closing as stale.
